### ISSUE TITLE
When I click on the cart icon, I should see summary of the cart

### ISSUE THREAD

**Issue by bkielbasa** [golang-app/ecommerce#33]
When a user clicks on the cart icon, and has some items in the cart, he should see up to 3 items in the cart, the total price, and a link to the `/cart` page.

When the cart is empty, it should just say that.

**Comment by Badrri-Narayanan** [comment]
Hi, can you please assign me this issue?

**Comment by bkielbasa** [comment]
@Badrri-Narayanan done!

**Comment by bkielbasa** [comment]
@Badrri-Narayanan do you need any help with the task?

**Comment by Badrri-Narayanan** [comment]
@bkielbasa , actually yes. The initial setup with docker-compose is not working. I tried using docker-compose command and it initially failed as there was no Dockerfile for frontend (I am using master branch). So, I added it and tried again, but when I started the react frontend, it gave me lots of typescript errors. So, I kept the other containers running and did a local setup of the frontend alone. But, I see no values in the homepage. So, I checked the network tab and I can see that the backend is not sending any records. 
![image](https://user-images.githubusercontent.com/26011119/229288226-0dcd1637-b798-4c23-9e5d-94fbc684fbe5.png)

On further investigation, I found that the inital seeding/creation of sample data is not working.
![image](https://user-images.githubusercontent.com/26011119/229288687-20c9072f-d050-43f0-8da8-cd2d8c166b6a.png)

Due to this, I am facing trouble recreating the issue. Can you please help?

**Comment by Badrri-Narayanan** [comment]
Also, Kibana is also failing to start as the initial setup sets and username and password.

**Comment by bkielbasa** [comment]
@Badrri-Narayanan sorry you had trouble with it.

I updated the master branch and added `seeds` service to docker-compose. You can run it with the following command:

```sh
docker-compose up seeds
```

It will populate the database with a few products. If you need more complex products please let me know. The project is in very early stage so we don't have any kind of back-office where we can manage the content.

I added the missing dockerfile to the front-end so if you run

```sh
docker-compose build
docker-compose up
```

in the project root folder, you should have everything up and running. You should see something like this

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/1235620/229345275-bddc99e0-cc45-4a18-8429-30f95a1a0b4a.png">


Please let me know if you have any problems with running everything. I'll be glad to help you out with it.
